### ISSUE TITLE
Add Collections header to Manuscript subject pages

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucdlib-wp-plugins#114]
This is a small change that's not crucial to add pre-launch as we are down to the wire at this point, but I think the manuscript subject pages would benefit from having a subheading appear after the description and prior to the subjects list. to improve readability/visual separation between description and manuscripts list.

### Example:

![Screen Shot 2022-08-12 at 2 06 52 PM](https://user-images.githubusercontent.com/17831969/184445177-e7a6848d-2afd-49a8-ac03-50d477415eb9.png)

**Comment by spelkey-ucd** [comment]
@wrenaria 

this is on sandbox:
https://sandbox.library.ucdavis.edu/archives-and-special-collections/collection-subject/agricultural-technology/

**Comment by wrenaria** [comment]
👍

**Comment by spelkey-ucd** [comment]
deployed to website_tag: v3.1.0
