### ISSUE TITLE
Hours date range issue

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ucdlib-wp-plugins#131]
On 2022-10-17, we started to see an issue with the library hours site, in that it wasn't displaying.  This was traced back to the communication between the client and server on the actual list of hours.  We performed an emergency patch on the production server:

**The patch has not been committed, and will fail if we need to change that container on the production site**

The line at: https://github.com/UCDavisLibrary/ucdlib-wp-plugins/blob/bd84d440c5a6011b365363cb43f7c38148602050/ucdlib-locations/includes/utils.php#L18

was changed to 
```javascript
    $end->modify('+' . $weeks . 'week')
``` 

This extended the range by one day, which immediately solved the problem.  But it's actually unclear why exactly this is not working now, and it has in the past.

In addition, the client code should be robust enough to not fail if the entire range of dates are not returned.

**Comment by qjhart** [comment]
@sbagg if you start developing w/out that change, you'll be able to save  the errors we are getting in the client code, and determine the best method to catch errors where the client is too fragile.

**Comment by spelkey-ucd** [comment]
Deployed main-wp-website@v3.2.0
