### ISSUE TITLE
Initial corpus of manuscripts and ua-collections

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ucdlib-wp-plugins#18]
The current website has different page types for manuscripts, ua-collections, and serials.  *serials* is not going to be included going forward, but manuscripts and ua-collections are going forward.  @wrenaria specified that the librarians want to use tha OAC archive, as the starting point, but allowing for changes to the title, or description for the webpage.

@wrenaria has [Implementation Notes](https://docs.google.com/document/d/1hWXyPkpo-u4v4hGOmc-t91spRnWfw_tiCXXb_PgUtk8/edit)

I've created a comparison of the OAC archive, and the library's current manuscripts  and ua-collections; [Summary Worksheet](https://docs.google.com/spreadsheets/d/18XDhenlmy8bAcujxFK8AcVxDFFPkOczqUVbV7TpaHU4/edit?usp=sharing)

Here are some notes about this. First, I guess our librarians think of these as separately belonging to two different OAC collections

manuscripts => https://oac.cdlib.org/institutions/UC+Davis::Special+Collections 
ua-collections => https://oac.cdlib.org/institutions/UC+Davis::University+Archives

Both of these are formatted the same, as a set of metadata embedded in the HTML document of the finding aid.  Since I don't know how these are maintained, I just wrote a [quick program](https://gist.github.com/qjhart/4ec619908a1caef17167e23b33283223) to fetch these from the OAC website.  It's mostly correct, but over the years multiple metadata keys where used for the same value, so I tried my best to collate these, but still needs some work.

For comparison, I pulled these both from the libraries website as well (also in the code).   The spreadsheet shows a few comparisons, and also, the extent to which the data fields are used.  This verifies a lot of @wrenaria's document as well.

Summary:
- There are a lot of items in OAC, that aren't on our current site
- There *are* some items that have only a brief OAC entry and no finding aid (no additioinal metadat), eg. [OAC](https://oac.cdlib.org/search?style=oac4;Institution=UC%20Davis::Special%20Collections;idT=UCD-000319568)[Library](https://www.library.ucdavis.edu/archives-and-special-collections/manuscript/our-lady-of-vladimir-convent-collection/),[ALMA](https://search.library.ucdavis.edu/discovery/fulldisplay?docid=alma990003195680403126&context=L&vid=01UCD_INST:UCD&lang=en&search_scope=DN_and_CI&adaptor=Local%20Search%20Engine&tab=UCSILSDefaultSearch&query=any,contains,mc120&mode=simple)
- Although there is no search-by-call_number on our primo site, a general site, usually does a pretty good job of finding the reference if it exists in Alma

Some notes:
- It might be best to use a slug that references these by call_number, so we don't have to make them manually
- arks are not a good alternative, since they don't exist for brief records
- We could use the union of these sets, and use library titles/ description where they differ
- We might try a `Get it At UC` link using a search on the call Number
- I forgot to harvest the tags from the library, I can do that if required
-

We can probably POST to the wp-api to add these when we are ready.
I'll leave for  @NeilWeingarten / @spelkey-ucd to specify next steps for getting the content organized.

**Comment by NeilWeingarten** [comment]
Next Steps:
  - Kimmy to talk to SPEC about page vs. card approach
  - Kimmy to talk to Quinn about info refresh from OAC
  - Quinn to harvest the tags, as we will need these.

We'll reconvene after these items are done to talk about further next steps.

**Comment by qjhart** [comment]
After meeting w/ @wrenaria, @spelkey-ucd , @NeilWeingarten, Kevin Miller, and Sara Gunasekara
 we decided that we were going to use the existing list of UA collections and archives that are currently in the library, and *not* use the pulled list from OAC.  

In preparation for that I added another sheet [combined by call_number](https://docs.google.com/spreadsheets/d/18XDhenlmy8bAcujxFK8AcVxDFFPkOczqUVbV7TpaHU4/edit#gid=637190209) to the [Summary Worksheet](https://docs.google.com/spreadsheets/d/18XDhenlmy8bAcujxFK8AcVxDFFPkOczqUVbV7TpaHU4/edit?usp=sharing) that includes a column `add` that identifies the records to add to the system.

Kevin and Sara are also going to talk to Jared about how the catalog entries are made, and whether their is a good method in primo for entry discovery.

Kevin's tentative plan is to not include anything that doesn't have a complete finding aid, so the workflow will be something like: 
1. Create a finding aid in  archive space
2. Upload to OAC
3. Create (or have created) a supporting ALMA record,
4. In the library website, add a new record by pasting in the permalink for the ALMA record, wordpress will parse that and create an initial record for the viewing

I also wrote a quick tool  to make the first best guess at alma record id, using this quick tool: 

```bash

```

The output of this was added to the

**Comment by qjhart** [comment]
After meeting w/ @wrenaria, @spelkey-ucd , @NeilWeingarten, Kevin Miller, and Sara Gunasekara
 we decided that we were going to use the existing list of UA collections and archives that are currently in the library, and *not* use the pulled list from OAC.  

In preparation for that I added another sheet [combined by call_number](https://docs.google.com/spreadsheets/d/18XDhenlmy8bAcujxFK8AcVxDFFPkOczqUVbV7TpaHU4/edit#gid=637190209) to the [Summary Worksheet](https://docs.google.com/spreadsheets/d/18XDhenlmy8bAcujxFK8AcVxDFFPkOczqUVbV7TpaHU4/edit?usp=sharing) that includes a column `add` that identifies the records to add to the system.

Kevin and Sara are also going to talk to Jared about how the catalog entries are made, and whether their is a good method in primo for entry discovery.

Kevin's tentative plan is to not include anything that doesn't have a complete finding aid, so the workflow will be something like: 
1. Create a finding aid in  archive space
2. Upload to OAC
3. Create (or have created) a supporting ALMA record,
4. In the library website, add a new record by pasting in the permalink for the ALMA record, wordpress will parse that and create an initial record for the viewing

I also wrote a quick tool  to make the first best guess at alma record id, using this quick tool: 

```bash

```

The output of this was added to the

**Comment by qjhart** [comment]
I don't want to spam Sara while she's on  vacation, but I just wanted to let you know that I've updated our shared google sheet with the pages Sara included.  I also used Jarad's MARCXML dumps to create a crosswalk page between Alma records and OAC finding aids. 

Finally, I reviewed the ArchiveSpace docs, and I'm pretty sure that the library website could use archive space as the source for creating the website entries as well as the alma record ids.  I'd imagine the alma interface might be a bit more convenient as we discussed, but they would both work, depending on the workflow you want.

**Comment by qjhart** [comment]
We are trying to finalize the technical plan for managing Special Collections manuscripts in the new website.

Recall that at our last meeting, we tentatively decided on a workflow where new additions to items in the special collections would be a path where an editor would add a primo permalink, that would use a call to the primosearch to autofill as much information as possible.  Subsequent to that, Jared provided a set of MARC records for special collections, and I created a crosswalk between alma records and existing items on the website.   This is all on the sheet we are sharing, https://docs.google.com/spreadsheets/d/18XDhenlmy8bAcujxFK8AcVxDFFPkOczqUVbV7TpaHU4/edit#gid=63719020

The first tab has a marker for items to initially add to the new site.  However, if you look at that list, you will find they do not all have alma records and/or finding aid(s), which goes against some of my previous notes, where Keviin had indicated they only wanted to add items w/ complete finding aids.   

Also, the plan will be to combine manuscripts and ua-collection items into a single type, on the new site.
I'm proposing these fields:

url/slug - Maybe based on the call number, as opposed to text (eg http://library.ucdavis.edu/special-collections/d-202)?
call number - required
featured image - optional 
extent - optional 
extent unit - pull-down ?  (or we could just have a field where both are entered "1.5 linear feet + special canister" 
finding aid - (link to oarchive)
description -
history - (somehow combine the biography/history of existing into one field, or maybe even add to above descsription)
alma record id - 
A list of related links - and titles
 
So:
- We need a list of the items to include in the new site originally
- Let me know if the workflow w/ the alma record is how you want to go
- Review the list of fields for items in the new site.

**Comment by qjhart** [comment]
@UcDust / @sbagg, it's time to start to create our JSON import scheme for the collections.  In our discussions w/ @spelkey-ucd , we've decided on creating a JSON stream for input.

It's my understanding that this JSON format be in the format that is used for adding posts via the wordpress API.  There are two methods that I can think of doing this: 
- We can create a JSON document directly from the [collections].  In this case, we'd create a javascript function to create this JSON.  The [ror] spreadsheet shows a good example of this 
- We could also create a new sheet, download that to CSV and convert to JSON. 

Off the cuff, I'd lean to the first solution.

We should start attempting imports into sandbox ASAP.

[collections]:
[ror]:https://docs.google.com/spreadsheets/d/1kuYdscy5Z1D-bLxTXppfljWBkLGjMu-CTh0EXZ-_sVI/edit?usp=sharing

**Comment by spelkey-ucd** [comment]
FYI, Justin has a separate repo where he has been doing migration work. Check in your scripts there.

https://github.com/UCDavisLibrary/wp-post-migration-tool
