### ISSUE TITLE
locations teaser block

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-wp-plugins#39]
locations teasers parent that allows 1+ teaser (singular) blocks

<img width="701" alt="image" src="https://user-images.githubusercontent.com/34284106/172664813-00bd2230-3eed-441a-bb67-7bbfa6cece1b.png">

https://xd.adobe.com/view/6d90f413-ef9f-4490-b82f-00e57098540f-38c3/

**Comment by wrenaria** [comment]
## Style Adjustments

**All main library blocks:**
- Need more space between items on main library previews

![Image](https://user-images.githubusercontent.com/17831969/176567752-2b84b34f-e8ed-41d8-9821-c8a1963b49f7.png)

**ASC:**
- ASC block is wrong shade of blue (too light) -- use `#ebf3fa` (same as background color blocks)
- Spacing on the ASC block is perfect though, do not alter.

![Image](https://user-images.githubusercontent.com/17831969/176566763-036f95d9-cd14-4e97-b6f5-49150297b3e2.png)

**Alert Spacing:**
- Crazy designer wants a tiny bit more space between address and alert cause it feels a smidge squished to me-- +0.25 rem is okay

![Image](https://user-images.githubusercontent.com/17831969/176567429-ee864e24-712a-4f70-b494-658285507ad6.png)
