### ISSUE TITLE
Import people profiles

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-wp-plugins#47]
Data are currently in [a google sheet](https://docs.google.com/spreadsheets/d/1rlOIqfAFm9kJnV_Yfrwc6FOPYQIGA1N5AicAQYQAOnc/edit#gid=1613327683).

They need to be imported as the `person` post type. 

Most data will be written to the [meta object](https://developer.wordpress.org/rest-api/reference/posts/#schema-meta). The keys [can be found here](https://github.com/UCDavisLibrary/ucdlib-wp-plugins/blob/sandbox/ucdlib-directory/includes/people.php#L148). In some cases, a metadata field is the post id of another post type, e.g. `position_dept`. 

Also, there are several taxonomies associated with the `person` post type:
- [Areas of Expertise](https://github.com/UCDavisLibrary/ucdlib-wp-plugins/blob/sandbox/ucdlib-directory/includes/areas-of-expertise.php)
- [Directory Tags](https://github.com/UCDavisLibrary/ucdlib-wp-plugins/blob/sandbox/ucdlib-directory/includes/directory-tags.php)
- [Libraries](https://github.com/UCDavisLibrary/ucdlib-wp-plugins/blob/sandbox/ucdlib-directory/includes/libraries.php)

All profiles should share the same template that is uploaded to the 'content' field:
```
<!-- wp:ucdlib-directory/name {"lock":{"move":true,"remove":true}} /-->

<!-- wp:ucdlib-directory/title {"lock":{"move":true,"remove":true}} /-->

<!-- wp:ucdlib-directory/pronouns {"lock":{"move":true,"remove":true}} /-->

<!-- wp:ucdlib-directory/contact {"lock":{"move":true,"remove":true}} /-->

<!-- wp:ucdlib-directory/library-locations {"lock":{"move":true,"remove":true}} /-->

<!-- wp:ucdlib-directory/bio {"lock":{"move":true,"remove":true}} /-->

<!-- wp:ucdlib-directory/expertise-areas {"lock":{"move":true,"remove":true}} /-->

<!-- wp:ucdlib-directory/tags {"lock":{"move":true,"remove":true}} /-->
```

**Comment by jrmerz** [comment]
@spelkey-ucd are the `position_dept` post types ready?  Or are uploading those post types part of this issue?

**Comment by spelkey-ucd** [comment]
I was thinking we would make stubs based on what is listed in the spreadsheet as part of the issue.

**Comment by spelkey-ucd** [comment]
yes, https://github.com/UCDavisLibrary/ucdlib-wp-plugins/blob/sandbox/ucdlib-directory/includes/departments.php

**Comment by spelkey-ucd** [comment]
@jrmerz Nice, mostly there. Here are the issues I found:

- Set title to first + last name
- `this.data.slug = clean(this.data.meta.username);` should be `clean(this.data.title)`
- We had a few peeps with missing/wrong kerbs. I filled them in the spreadsheet, so download it again before reimporting.
- Areas of expertise made it in, but are not attached to any people
- Looks like none of the Subject Areas were imported as Directory Tags
- Access and Delivery Services got imported twice. Looks to be the only one.
- Getting some additional crud when a person has an 'other' website:
```        "contactWebsite": [
            {
                "type": "other",
                "value": "https:\/\/github.com\/spelkey-ucd",
                "label": "Other"
            },
            {
                "type": "",
                "label": "professional website or blog"
            },
            {
                "type": "",
                "label": "or a playlist of instructional videos)"
            }
        ],```

**Comment by jrmerz** [comment]
@spelkey-ucd data reimported into sandbox with changes above. let me know how things look.

**Comment by spelkey-ucd** [comment]
@jrmerz  a couple issues:

## 1
still getting crud when someone has 'other' website listed: https://sandbox.library.ucdavis.edu/wp-json/ucdlib-directory/person/spelkey@ucdavis.edu

## 2

departments got duplicated and are drafts:

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/34284106/177405311-1388a2e0-4328-43bd-9287-1c8f2b506c1c.png">

[Dale](https://sandbox.library.ucdavis.edu/wp-json/ucdlib-directory/person/dfsnapp@ucdavis.edu) and [I](https://sandbox.library.ucdavis.edu/wp-json/ucdlib-directory/person/spelkey@ucdavis.edu) are attached to different versions of ITIS. Interestingly, this didnt happen to everyone since there are 131 people and 87 departments.

## 3
In the post template, there is an extra `s` on `wp:ucdlib-directory/expertise-areas` which causes wp not to recognize the block: 
<img width="985" alt="image" src="https://user-images.githubusercontent.com/34284106/177406315-1743c892-35e7-4cdb-a314-dd1b95668db7.png">
