### ISSUE TITLE
Form Radio Button lists opposite

### ISSUE THREAD

**Issue by NeilWeingarten** [UCDavisLibrary/ucdlib-wp-plugins#48]

**Comment by NeilWeingarten** [comment]
odd behavior in forms: radio button lists are loading their values in opposite order when actually viewed in a page.  See the class request form as an example: https://stage.library.ucdavis.edu/wp-admin/admin.php?page=forminator-cform-wizard&id=8690  vs. https://stage.library.ucdavis.edu/?page_id=8582&preview=true

**Comment by NeilWeingarten** [comment]
Checking in on this - any estimate on when a resolution will be in place (pending deployment fix)?

**Comment by spelkey-ucd** [comment]
This should be fixed on stage.
