### ISSUE TITLE
Register Exhibit metadata

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-wp-plugins#49]
## isOnline
**type:** checkbox
**conditionally displayed?** no

## isPhysical
**type:** checkbox
**conditionally displayed?** no

## isPermanent
**type:** checkbox
**conditionally displayed?** if `isPhysical==true`

## dateFrom
**type:** date
**conditionally displayed?** if `isPhysical==true and not isPermanent`

## dateTo
**type:** date
**conditionally displayed?** if `isPhysical==true and not isPermanent`

## curatingOrg
**type:** controlled taxonomy
**conditionally displayed?** no
**choices**:
- Archives and Special Collections
- Student Services
- UC Davis Library
- etc

## curators
**type** multi select of people from directory
**conditionally displayed?** no

## locationText
**type:** Controlled taxonomy
**conditionally displayed?** if `isPhysical==true`

## locationDirections
**type:** String
**conditionally displayed?** if `isPhysical==true`

## locationMap
**type:** WP Image ID
**conditionally displayed?** if `isPhysical==true`

**Comment by spelkey-ucd** [comment]
@wrenaria do these metadata fields look right? 

Can an online exhibit ALSO be a past exhibit? im assuming no?

**Comment by wrenaria** [comment]
@spelkey An online exhibit actually _can_ be a past exhibit if at one point it had a physical display! For example, Saratoga is an online exhibit that was formerly on display in the library in 2008. Same with Unitrans.

You can see on the [current Unitrans exhibit](https://www.library.ucdavis.edu/exhibit/unitrans-40-moving-students-decades/) there is some tiny text that says "Previously on display Jan 5 - Apr 6, 2008 in Shields Library Lobby - Special Collections"

For these items, they would be findable in "past" list as well as in "online" list. For the sidebar, we would **not** show the location map for past exhibits that persist online, but there would be a small text acknowledgement denoting date and the library in which it was displayed.

![Screen Shot 2022-06-24 at 1 41 57 PM](https://user-images.githubusercontent.com/17831969/175664390-cdbaa4e2-edcd-4895-8708-89d87e2f316c.png)
