### ISSUE TITLE
Single Exhibit Template

### ISSUE THREAD

**Issue by spelkey-ucd** [UCDavisLibrary/ucdlib-wp-plugins#50]
Need a custom twig template and potentially a semi-locked block template.

Exhibits can be hierarchical, which requires some custom templating:
- breadcrumbs must display exhibits lander
- an automatically generated subnav for that exhibit. 
- buttons at bottom of page for navigating to previous and next pages

Possible sidebar blocks include:
- subnav #51 
- curated by box (also has when displayed if past exhibit) #52 
- exhibit location (for active physical exhibits) #53

**Comment by spelkey-ucd** [comment]
@wrenaria for the exhibit sidebar, would you prefer:

1. It to be controlled by the individual exhibit pages? We can lock the applicable required blocks (subnav, curators, location), but the authors will be able to put in custom content above, below, and between these widgets.
2. or for it be controlled by a [registered widget area](https://wordpress.org/support/article/wordpress-widgets/#displaying-widgets). Only admin will be able to choose what is displayed, and changes are applied to all exhibit pages. Widgets could still be conditionally displayed (e.g. no location block on online exhibits). But, authors would only see the main content area in the editor.

**Comment by wrenaria** [comment]
@spelkey Option 2, I think. I'd like to keep the sidebar from accumulating extra clutter, since the required fields fill up pretty well as it is.
