### ISSUE TITLE
Forms are not emailing to assigned emails when submitted

### ISSUE THREAD

**Issue by NeilWeingarten** [UCDavisLibrary/ucdlib-wp-plugins#64]

**Comment by NeilWeingarten** [comment]
Both DDS forms and the suggest a purchase form have had tests submitted and are not emailing to their assigned email recipients - I'm assuming this applies to all other forms.  The submissions are showing in the form plugin.  Test form page: https://stage.library.ucdavis.edu/test-form-page/

**Comment by spelkey-ucd** [comment]
@NeilWeingarten this appears to be working. check your spam folder.

**Comment by NeilWeingarten** [comment]
@spelkey-ucd Justin fixed this a while back - closing the issue.
